export const CREATE_ORDER = 'CREATE_ORDER';
export const ADD_BUYER_INFO = 'ADD_BUYER_INFO';
export const CLEAR_ORDER = "CLEAR_ORDER"
export const SET_PAYMENT_METHOD ="SET_PAYMENT_METHOD"
export const SAVE_ORDER_CONFIRMATION ="SAVE_ORDER_CONFIRMATION"

