//Search
export const SAVE_SEARCH_INPUT = 'SAVE_SEARCH_INPUT';
export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS';
export const FETCH_SEARCH_ERROR = 'FETCH_SEARCH_ERROR';
//order
export const CREATE_ORDER = 'CREATE_ORDER';
export const ADD_BUYER_INFO = 'ADD_BUYER_INFO';
export const CLEAR_ORDER = "CLEAR_ORDER"
export const SET_PAYMENT_METHOD ="SET_PAYMENT_METHOD"
export const SAVE_ORDER_CONFIRMATION ="SAVE_ORDER_CONFIRMATION"
//Cart
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const SUB_QUANTITY = 'SUB_QUANTITY';
export const ADD_QUANTITY = 'ADD_QUANTITY';
export const ADD_SHIPPING = 'ADD_SHIPPING';
export const CLEAR_CART = 'CLEAR_CART';
export const SAVE_DATA = "SAVE_DATA"
//review
export const CREATE_REVIEW = "CREATE_REVIEW"
export const SAVE_REVIEWS = "SAVE_REVIEWS"
export const APPEND_REVIEW = "APPEND_REVIEW"
export const SUCCESSFUL = "SUCCESSFUL"
export const FAILED = "FAILED"
export const SAVE_PRODUCT_ID = "SAVE_PRODUCT_ID"
export const ADD_RATING = "ADD_RATING"
//currency
export const UPDATE_CURRENCY = "UPDATE_CURRENCY"